base.url=https://practicetestautomation.com/practice-test-login/
username=student
password=Password123
browser=chromium
wrongPassword=WrongPass123
wrongUsername=WrongUsername123
emptyPassword=
emptyUsername=